"""empty message

Revision ID: 604b7f3241e9
Revises: ca872dcf67a9
Create Date: 2024-03-03 12:33:43.581395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604b7f3241e9'
down_revision = 'ca872dcf67a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deck', sa.Text, nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_status', schema=None) as batch_op:
        batch_op.drop_column('deck')

    # ### end Alembic commands ###
