"""empty message

Revision ID: 66e43fff68da
Revises: 5a76632c0272
Create Date: 2024-03-07 20:22:34.844425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66e43fff68da'
down_revision = '5a76632c0272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_decision', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_status', schema=None) as batch_op:
        batch_op.drop_column('player_decision')

    # ### end Alembic commands ###
