"""empty message

Revision ID: a5c30de62223
Revises: 66e43fff68da
Create Date: 2024-03-09 14:31:44.195338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5c30de62223'
down_revision = '66e43fff68da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_status', schema=None) as batch_op:
        batch_op.alter_column('player_decision',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_status', schema=None) as batch_op:
        batch_op.alter_column('player_decision',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
