"""empty message

Revision ID: b680863abd1e
Revises: 
Create Date: 2024-03-18 22:47:04.666922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b680863abd1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_status', schema=None) as batch_op:
        batch_op.drop_index('ix_game_status_game_id')

    op.drop_table('game_status')
    op.drop_table('game')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('token_expiration', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_token'), ['token'], unique=True)
        batch_op.drop_column('balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.NUMERIC(precision=10, scale=2), nullable=False))
        batch_op.drop_index(batch_op.f('ix_user_token'))
        batch_op.drop_column('token_expiration')
        batch_op.drop_column('token')

    op.create_table('game',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('game_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('winner', sa.VARCHAR(length=25), nullable=False),
    sa.Column('bet', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_status',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('game_id', sa.INTEGER(), nullable=False),
    sa.Column('player_hand', sa.VARCHAR(length=250), nullable=False),
    sa.Column('dealer_hand', sa.VARCHAR(length=250), nullable=False),
    sa.Column('game_status', sa.VARCHAR(length=250), nullable=False),
    sa.Column('dealer_score', sa.INTEGER(), nullable=False),
    sa.Column('player_score', sa.INTEGER(), nullable=False),
    sa.Column('deck', sa.TEXT(), nullable=False),
    sa.Column('player_decision', sa.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_status', schema=None) as batch_op:
        batch_op.create_index('ix_game_status_game_id', ['game_id'], unique=False)

    # ### end Alembic commands ###
